$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  
  staggered:
    type: boolean

  plate:
    type: object
    properties:
      num_wells:
        type: integer
      well_settings:
        type: string
      ab_settings:
        type: string
    required:
      - well_settings
      - ab_settings
        